name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - run: echo ${{ secrets.LOCAL_RUNNER_ENV }}
    - run:  echo ${{ secrets.LOCAL_RUNNER_ENV }} | base64 --decode > .env
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        cache: 'npm'
    - run: npm ci
    - run: npm run start --if-present
    - run: npm test

    #  - name: Set up env file
    #   env:
    #     LOCAL_RUNNER_ENV: ${{ secrets.LOCAL_RUNNER_ENV }}
    #   run: |
    #     echo $LOCAL_RUNNER_ENV >> .env